In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np
from modules import transfer_entropy as TE

In [2]:
lista = ["Atlanta-Sandy Springs-Alpharetta, GA MSA",
    "Baltimore-Columbia-Towson, MD MSA",
    "Boston-Cambridge-Newton, MA-NH MSA",
    "Chicago-Naperville-Elgin, IL-IN-WI MSA",
    "Dallas-Fort Worth-Arlington, TX MSA",
    "Denver-Aurora-Lakewood, CO MSA",
    "Detroit_Dearborn, MI MSA",
    "Houston-The Woodlands-Sugar Land, TX MSA",
    "Los Angeles-Long Beach-Anaheim, CA MSA",
    "Miami-Fort Lauderdale-West Palm Beach, FL MSA",
    "Minneapolis-St. Paul-Bloomington, MN-WI MSA",
    "New York-Newark-Jersey City, NY-NJ-PA MSA",
    "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD MSA",
    "Phoenix-Mesa-Chandler, AZ MSA",
    "Riverside-San Bernardino-Ontario, CA MSA",
    "San Francisco-Oakland-Berkeley, CA MSA",
    "Tampa-St. Petersburg-Clearwater, FL MSA",
    "Washington-Arlington-Alexandria, DC-VA-MD-WV MSA"]
df = pd.read_csv("data/Times_series_sa_det.csv")

The p-values given in the paper were computed with iterations = 20,000

In [3]:
for arg in lista:
    Positive_Tweets = TE.Median_Symbolise_3bins(df["Tweet search - "+arg+"_sentNumber_Positive_sa_det"])
    Negative_Tweets = TE.Median_Symbolise_3bins(df["Tweet search - "+arg+"_sentNumber_Negative_sa_det"])
    crimes =          TE.Median_Symbolise_3bins(df[arg+"_crimes_lagged_sa_det"])
    Police_brutality =TE.Median_Symbolise_3bins(df["Police_Brutality_lagged_sa_det"])
    results = TE.ComputeH1H2_lags(PB = Police_brutality,CR = crimes,
                             PT = Positive_Tweets,NT = Negative_Tweets,iterations = 100)    
    print(arg)
    display(results)

Atlanta-Sandy Springs-Alpharetta, GA MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.005768,0.009254,0.801980,target1 source1 condition1
1,Crimes,negative Tweets,0.030127,0.032784,0.297030,target1 source2 condition1
2,Crimes,negative Tweets,0.022105,0.027060,0.425743,target1 source1 condition2
3,Crimes,Positive Tweets,0.007379,0.009970,0.405941,target1 source1 condition1
4,Crimes,Positive Tweets,0.033444,0.033565,0.069307,target1 source2 condition1
5,Crimes,Positive Tweets,0.021107,0.026477,0.584158,target1 source1 condition2
6,Police brut,Negative Tweets,0.025607,0.009855,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.053056,0.034931,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.044688,0.026293,0.000000,target1 source1 condition2

Baltimore-Columbia-Towson, MD MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.005896,0.009593,0.702970,target1 source1 condition1
1,Crimes,negative Tweets,0.027522,0.032755,0.584158,target1 source2 condition1
2,Crimes,negative Tweets,0.017769,0.027564,0.910891,target1 source1 condition2
3,Crimes,Positive Tweets,0.006939,0.010136,0.485149,target1 source1 condition1
4,Crimes,Positive Tweets,0.023762,0.033220,0.891089,target1 source2 condition1
5,Crimes,Positive Tweets,0.018026,0.026544,0.881188,target1 source1 condition2
6,Police brut,Negative Tweets,0.010767,0.009924,0.029703,target1 source1 condition1
7,Police brut,Negative Tweets,0.031465,0.033720,0.207921,target1 source2 condition1
8,Police brut,Negative Tweets,0.026216,0.028658,0.099010,target1 source1 condition2

Boston-Cambridge-Newton, MA-NH MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.004199,0.010122,0.980198,target1 source1 condition1
1,Crimes,negative Tweets,0.025212,0.034329,0.861386,target1 source2 condition1
2,Crimes,negative Tweets,0.020019,0.026578,0.742574,target1 source1 condition2
3,Crimes,Positive Tweets,0.006039,0.009782,0.653465,target1 source1 condition1
4,Crimes,Positive Tweets,0.029690,0.034893,0.326733,target1 source2 condition1
5,Crimes,Positive Tweets,0.020844,0.026438,0.594059,target1 source1 condition2
6,Police brut,Negative Tweets,0.019113,0.010137,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.043773,0.034181,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.031767,0.027024,0.019802,target1 source1 condition2

Chicago-Naperville-Elgin, IL-IN-WI MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.007029,0.009967,0.425743,target1 source1 condition1
1,Crimes,negative Tweets,0.025021,0.034108,0.871287,target1 source2 condition1
2,Crimes,negative Tweets,0.023818,0.026647,0.287129,target1 source1 condition2
3,Crimes,Positive Tweets,0.007136,0.009819,0.356436,target1 source1 condition1
4,Crimes,Positive Tweets,0.027985,0.035226,0.534653,target1 source2 condition1
5,Crimes,Positive Tweets,0.022071,0.025923,0.485149,target1 source1 condition2
6,Police brut,Negative Tweets,0.023449,0.009506,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.053042,0.034709,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.034345,0.027014,0.000000,target1 source1 condition2

Dallas-Fort Worth-Arlington, TX MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.006114,0.009458,0.653465,target1 source1 condition1
1,Crimes,negative Tweets,0.025886,0.033995,0.782178,target1 source2 condition1
2,Crimes,negative Tweets,0.017810,0.027699,0.900990,target1 source1 condition2
3,Crimes,Positive Tweets,0.007301,0.009594,0.435644,target1 source1 condition1
4,Crimes,Positive Tweets,0.026003,0.032117,0.762376,target1 source2 condition1
5,Crimes,Positive Tweets,0.020270,0.026114,0.643564,target1 source1 condition2
6,Police brut,Negative Tweets,0.037812,0.010097,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.058256,0.035240,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.049748,0.025854,0.000000,target1 source1 condition2

Denver-Aurora-Lakewood, CO MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.007494,0.009983,0.316832,target1 source1 condition1
1,Crimes,negative Tweets,0.032725,0.033271,0.069307,target1 source2 condition1
2,Crimes,negative Tweets,0.019558,0.027001,0.772277,target1 source1 condition2
3,Crimes,Positive Tweets,0.008261,0.010206,0.217822,target1 source1 condition1
4,Crimes,Positive Tweets,0.024054,0.034613,0.940594,target1 source2 condition1
5,Crimes,Positive Tweets,0.019921,0.027034,0.613861,target1 source1 condition2
6,Police brut,Negative Tweets,0.023655,0.009890,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.044607,0.035099,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.040370,0.025775,0.000000,target1 source1 condition2

Detroit_Dearborn, MI MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.006324,0.010290,0.683168,target1 source1 condition1
1,Crimes,negative Tweets,0.031553,0.035383,0.178218,target1 source2 condition1
2,Crimes,negative Tweets,0.019903,0.026193,0.782178,target1 source1 condition2
3,Crimes,Positive Tweets,0.006713,0.011006,0.594059,target1 source1 condition1
4,Crimes,Positive Tweets,0.026578,0.034386,0.693069,target1 source2 condition1
5,Crimes,Positive Tweets,0.019856,0.028079,0.683168,target1 source1 condition2
6,Police brut,Negative Tweets,0.024627,0.009655,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.047102,0.034573,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.041518,0.026843,0.000000,target1 source1 condition2

Houston-The Woodlands-Sugar Land, TX MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.008438,0.010184,0.247525,target1 source1 condition1
1,Crimes,negative Tweets,0.027521,0.033606,0.663366,target1 source2 condition1
2,Crimes,negative Tweets,0.025790,0.026415,0.108911,target1 source1 condition2
3,Crimes,Positive Tweets,0.005970,0.010387,0.702970,target1 source1 condition1
4,Crimes,Positive Tweets,0.025678,0.034182,0.821782,target1 source2 condition1
5,Crimes,Positive Tweets,0.023260,0.028724,0.405941,target1 source1 condition2
6,Police brut,Negative Tweets,0.014571,0.010015,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.043265,0.036162,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.028816,0.026377,0.009901,target1 source1 condition2

Los Angeles-Long Beach-Anaheim, CA MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.010385,0.010234,0.039604,target1 source1 condition1
1,Crimes,negative Tweets,0.033899,0.033488,0.039604,target1 source2 condition1
2,Crimes,negative Tweets,0.027537,0.027891,0.069307,target1 source1 condition2
3,Crimes,Positive Tweets,0.007192,0.009834,0.405941,target1 source1 condition1
4,Crimes,Positive Tweets,0.033754,0.035965,0.198020,target1 source2 condition1
5,Crimes,Positive Tweets,0.022872,0.028151,0.455446,target1 source1 condition2
6,Police brut,Negative Tweets,0.030305,0.010058,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.058347,0.035525,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.044907,0.027390,0.000000,target1 source1 condition2

Miami-Fort Lauderdale-West Palm Beach, FL MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.006949,0.010044,0.445545,target1 source1 condition1
1,Crimes,negative Tweets,0.033864,0.034849,0.069307,target1 source2 condition1
2,Crimes,negative Tweets,0.020630,0.025557,0.544554,target1 source1 condition2
3,Crimes,Positive Tweets,0.003882,0.009090,0.970297,target1 source1 condition1
4,Crimes,Positive Tweets,0.030607,0.033252,0.207921,target1 source2 condition1
5,Crimes,Positive Tweets,0.015312,0.026974,0.980198,target1 source1 condition2
6,Police brut,Negative Tweets,0.036126,0.010012,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.064029,0.035622,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.049207,0.026210,0.000000,target1 source1 condition2

Minneapolis-St. Paul-Bloomington, MN-WI MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.009669,0.009617,0.049505,target1 source1 condition1
1,Crimes,negative Tweets,0.032531,0.033555,0.099010,target1 source2 condition1
2,Crimes,negative Tweets,0.028139,0.026364,0.029703,target1 source1 condition2
3,Crimes,Positive Tweets,0.009466,0.009096,0.039604,target1 source1 condition1
4,Crimes,Positive Tweets,0.025863,0.033360,0.722772,target1 source2 condition1
5,Crimes,Positive Tweets,0.023307,0.026276,0.257426,target1 source1 condition2
6,Police brut,Negative Tweets,0.037648,0.010055,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.066284,0.035770,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.053970,0.026431,0.000000,target1 source1 condition2

New York-Newark-Jersey City, NY-NJ-PA MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.006588,0.009866,0.594059,target1 source1 condition1
1,Crimes,negative Tweets,0.032151,0.035249,0.168317,target1 source2 condition1
2,Crimes,negative Tweets,0.020846,0.027604,0.663366,target1 source1 condition2
3,Crimes,Positive Tweets,0.009123,0.009067,0.049505,target1 source1 condition1
4,Crimes,Positive Tweets,0.032339,0.033151,0.069307,target1 source2 condition1
5,Crimes,Positive Tweets,0.025027,0.026217,0.099010,target1 source1 condition2
6,Police brut,Negative Tweets,0.026516,0.010412,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.051211,0.033941,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.042729,0.027761,0.000000,target1 source1 condition2

Philadelphia-Camden-Wilmington, PA-NJ-DE-MD MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.006968,0.009444,0.475248,target1 source1 condition1
1,Crimes,negative Tweets,0.034883,0.034087,0.049505,target1 source2 condition1
2,Crimes,negative Tweets,0.020343,0.026636,0.643564,target1 source1 condition2
3,Crimes,Positive Tweets,0.006317,0.009569,0.594059,target1 source1 condition1
4,Crimes,Positive Tweets,0.027157,0.035047,0.633663,target1 source2 condition1
5,Crimes,Positive Tweets,0.025629,0.026016,0.079208,target1 source1 condition2
6,Police brut,Negative Tweets,0.024149,0.009619,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.045706,0.033670,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.045455,0.027740,0.000000,target1 source1 condition2

Phoenix-Mesa-Chandler, AZ MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.007505,0.010630,0.366337,target1 source1 condition1
1,Crimes,negative Tweets,0.029227,0.032950,0.445545,target1 source2 condition1
2,Crimes,negative Tweets,0.022143,0.027103,0.584158,target1 source1 condition2
3,Crimes,Positive Tweets,0.007913,0.009378,0.277228,target1 source1 condition1
4,Crimes,Positive Tweets,0.024152,0.033345,0.891089,target1 source2 condition1
5,Crimes,Positive Tweets,0.026029,0.027135,0.059406,target1 source1 condition2
6,Police brut,Negative Tweets,0.024487,0.010059,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.048434,0.035011,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.039808,0.025740,0.000000,target1 source1 condition2

Riverside-San Bernardino-Ontario, CA MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.010119,0.009350,0.009901,target1 source1 condition1
1,Crimes,negative Tweets,0.032120,0.035161,0.237624,target1 source2 condition1
2,Crimes,negative Tweets,0.024609,0.027310,0.247525,target1 source1 condition2
3,Crimes,Positive Tweets,0.007239,0.010034,0.415842,target1 source1 condition1
4,Crimes,Positive Tweets,0.026869,0.033975,0.722772,target1 source2 condition1
5,Crimes,Positive Tweets,0.024799,0.025518,0.099010,target1 source1 condition2
6,Police brut,Negative Tweets,0.023971,0.009790,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.049064,0.036563,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.037400,0.026367,0.000000,target1 source1 condition2

San Francisco-Oakland-Berkeley, CA MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.006794,0.010112,0.485149,target1 source1 condition1
1,Crimes,negative Tweets,0.027980,0.033624,0.495050,target1 source2 condition1
2,Crimes,negative Tweets,0.020527,0.026805,0.693069,target1 source1 condition2
3,Crimes,Positive Tweets,0.006109,0.009266,0.693069,target1 source1 condition1
4,Crimes,Positive Tweets,0.031876,0.036140,0.207921,target1 source2 condition1
5,Crimes,Positive Tweets,0.014525,0.026150,0.990099,target1 source1 condition2
6,Police brut,Negative Tweets,0.020958,0.009725,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.046285,0.037447,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.034948,0.025639,0.000000,target1 source1 condition2

Tampa-St. Petersburg-Clearwater, FL MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.004787,0.009021,0.950495,target1 source1 condition1
1,Crimes,negative Tweets,0.026775,0.033368,0.702970,target1 source2 condition1
2,Crimes,negative Tweets,0.018911,0.026984,0.821782,target1 source1 condition2
3,Crimes,Positive Tweets,0.008297,0.010060,0.267327,target1 source1 condition1
4,Crimes,Positive Tweets,0.029604,0.034980,0.346535,target1 source2 condition1
5,Crimes,Positive Tweets,0.022081,0.026821,0.455446,target1 source1 condition2
6,Police brut,Negative Tweets,0.032286,0.009771,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.062045,0.034507,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.045213,0.026560,0.000000,target1 source1 condition2

Washington-Arlington-Alexandria, DC-VA-MD-WV MSA

,Source,Target,TE,Quantile,p_val,lags
0,Crimes,negative Tweets,0.006767,0.009636,0.485149,target1 source1 condition1
1,Crimes,negative Tweets,0.029141,0.034370,0.475248,target1 source2 condition1
2,Crimes,negative Tweets,0.020816,0.027569,0.653465,target1 source1 condition2
3,Crimes,Positive Tweets,0.008909,0.009047,0.079208,target1 source1 condition1
4,Crimes,Positive Tweets,0.026970,0.033461,0.693069,target1 source2 condition1
5,Crimes,Positive Tweets,0.018725,0.026660,0.811881,target1 source1 condition2
6,Police brut,Negative Tweets,0.024130,0.010222,0.000000,target1 source1 condition1
7,Police brut,Negative Tweets,0.048383,0.034549,0.000000,target1 source2 condition1
8,Police brut,Negative Tweets,0.039219,0.025783,0.000000,target1 source1 condition2

In [4]:
print("Pandas version:",pd.__version__)
print("Numpy version:",np.__version__)

Pandas version: 1.4.2
Numpy version: 1.21.6